// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    C59Alert: typeof import('./src/components/c59-alert.vue')['default']
    C59Button: typeof import('./src/components/c59-button.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
  }
}
